<?php

/**
 * @file
 * Provides basic integration with the Yotpo API.
 */

/**
 * Implements hook_menu().
 */
function yotpo_menu() {
  $items = array();
  $items['admin/config/services/yotpo'] = array(
    'title' => 'Yotpo',
    'description' => 'Configure settings associated with Yotpo.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('variable_group_form', 'yotpo'),
    'access arguments' => array('administer site configuration'),
  );
  return $items;
}

/**
 * Implements hook_libraries_info().
 */
function yotpo_libraries_info() {
  $libraries['yotpo-php'] = array(
    'name' => 'Yotpo PHP Library (yotpo-php)',
    'vendor url' => 'https://github.com/Travelopia/yotpo-php',
    'download url' => 'https://github.com/amanaplan/yotpo-php/archive/build-v1.0.4.zip',
    'version callback' => 'yotpo_get_version',
    'files' => array(
      'php' => array(
        'bootstrap.php',
      ),
    ),
  );
  return $libraries;
}

/**
 * Version callback for libraries integration.
 *
 * @return string|FALSE
 *   If a version is detected, returns the version number as a string.
 *   Otherwise, returns FALSE.
 */
function yotpo_get_version($library) {
  require_once DRUPAL_ROOT . '/' . $library['library path'] . '/bootstrap.php';
  if (defined('\Yotpo\Yotpo::VERSION')) {
    return \Yotpo\Yotpo::VERSION;
  }
  return FALSE;
}

/**
 * Loads the yotpo-php library.
 *
 * @return boolean
 *   Returns a boolean indicating whether the library was successfully loaded.
 */
function yotpo_load() {
  // Try to load the library and check if that worked.
  if (($library = libraries_load('yotpo-php')) && !empty($library['loaded'])) {
    if (class_exists('Yotpo')) {
      return TRUE;
    }
  }
  return FALSE;
}

/**
 * Creates and initializes a new instance of the Yotpo class.
 *
 * @return object|FALSE
 *   If the library is successfully loaded, returns a Yotpo object.
 *   Otherwise, returns FALSE.
 */
function yotpo_get_instance() {
  if (yotpo_load()) {
    $id = variable_get('commerce_yotpo_api_key');
    $secret = variable_get('commerce_yotpo_api_secret');
    $yotpo = new Yotpo($id, $secret);
    return $yotpo;
  }
  return FALSE;
}
